### ISSUE TITLE
Reload Apps button doesn't reload from Apps server

### ISSUE THREAD

**Issue by schiguoi** [zendesk/zcli#12]
## Expectations

1. Click the Reload Apps button
1. The locally tested app should refresh with the most up to date code

## Reality

1. Click the Reload Apps button
1. All of my installed apps load, the locally tested app does not load
1. Refreshing the browser page (using the `?zcli_apps=true` url) using the browser controls loads the locally tested app as expected

## Steps to Reproduce

1. Run `zcli apps:server`
1. Navigate to https://{subdomain}.zendesk.com/agent/tickets/123?zcli_apps=true
1. Update code
1. Click Reload Apps button
1. Observe all installed apps load instead of app being tested
1. Click refresh button in browser
1. Observe app being tested load as expected

### Issue details

- Command: `zcli apps:server`
- Version: @zendesk/zcli/1.0.0-beta.4 darwin-x64 node-v12.18.3
- OS: macOS Catalina 10.15.6, Google Chrome 84.0.4147.135

**Comment by sostopher** [comment]
Hey Dan, 

Thanks for the feedback! This is in progress of being fixed 🚧 , I'll update this issue once it's out. 

Chris

**Comment by sakaruk** [comment]
This happens in one more condition ... When zcli_apps=true and you install an new private app all the installed apps shows up instead of the local app of zcli_apps=true. I think this is the same condition for the reloading the app

**Comment by etanxing** [comment]
Hey @schiguoi and @sakaruk, I just verified this issue and it's fixed now. Thanks
