### ISSUE TITLE
Locations are not loaded even if the server is running without issues

### ISSUE THREAD

**Issue by sarates** [zendesk/zcli#138]
## Expectations

Locations should be rendered properly when zcli server is started.

## Reality

The server is running without any issues, but locations like top_bar, ticket_sidebar, etc are not loaded.
The **problems appeared only today**, yesterday everything was working fine.

## Steps to Reproduce

1. run the server `zcli apps:server {app_directory}`
2. check the UI `https://{subdomain}.zendesk.com/agent/tickets/{123}?zcli_apps=true`

### Issue details

- OS: MAC
- Version:  `@zendesk/zcli/1.0.0-beta.23 darwin-arm64 node-v18.9.0`

**Comment by Vokinloksar** [comment]
same issue here.

**Comment by FlorianMarckmann** [comment]
same issue here. Yesterday all was good

**Comment by voidjumper** [comment]
facing the same issue

**Comment by ArturPerun** [comment]
facing the same issue

**Comment by andrii-ivaniuk** [comment]
The same issue. I don't see my app on nav bar.
```
"location": {
    "support": {
      "nav_bar": {
```

**Comment by augustobritodev** [comment]
same problem here! apps are not loading inside zendesk

**Comment by bkw** [comment]
Chrome console logs this:

> app_loader_fallback.ts?3f61:24 Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:4567/app.json?locale=en&subdomain=XXXX with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

FIrefox logs this:

> The script from “http://localhost:4567/app.json?locale=en&subdomain=XXXX” was loaded even though its MIME type (“application/json”) is not a valid JavaScript MIME type. [[Learn More](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)]

**Comment by bkw** [comment]
It's a problem with the javascript on the zendesk server side. They changed the way the app.json is loaded from localhost when `zli_apps=true` is present in the query; it is being injected as a script now, which fails, because it is a json file.

We can only hope some person within Zendesk sees this and opens an urgent issue on their internal bug tracker to reverse whatever change they deployed yesterday.

/CC: @sostopher @zach-anthony

**Comment by pedrobeto** [comment]
Facing the same issue on Ubuntu 20.04.

**Comment by VitorPeixoto** [comment]
I'm experiencing the same problem here. We managed to run the app normally using [ZAT](https://developer.zendesk.com/documentation/apps/zendesk-app-tools-zat/installing-and-using-zat/) with `zat=true` on the query as a temporary solution, but with zcli the app still does not load.

**Comment by jbarmanet** [comment]
Hi @zach-anthony as I'm experiencing the same issue today, I was wondering if the fix was made on Zendesk side, or if it has anything to do with a specific zcli version?

**Comment by cylwin** [comment]
I have this same issue again today.
@zach-anthony
