### ISSUE TITLE
I can't create app using the cli 

### ISSUE THREAD

**Issue by NeoArcanjo** [zendesk/zcli#155]
## Expectations
Create a new app

## Reality
    TypeError: Cannot read properties of undefined (reading 'ux')
<img width="505" alt="image" src="https://user-images.githubusercontent.com/44139615/213474083-8492178a-ad48-4e42-ae92-3ac6753513b6.png">

## Steps to Reproduce

1. Running Zcli at ubuntu 22 under wsl using nodejs under asdf

### Issue details

- Command:  zcli apps:new 
- Version: @zendesk/zcli/1.0.0-beta.28 wsl-x64 node-v18.12.1
- OS: Ubuntu 22.04.1 (WSL)

**Comment by dalenleung** [comment]
I'm experiencing the same issue as well

<img width="571" alt="image" src="https://user-images.githubusercontent.com/13922058/213624345-dcc41d2c-772d-4d58-968f-4e45e64967ca.png">


Command: Any zcli command is giving me the same error message
ZCLI Version: @zendesk/zcli/1.0.0-beta.28
Node Version: v18.11.0
OS: Apple M1 Max Ventura 13.1 (22C65)

**Comment by schuob** [comment]
Same here - was working before this new beta.
![Screenshot 2023-01-19 at 11 05 05 PM](https://user-images.githubusercontent.com/11069290/213637092-0dc15c3b-7d2b-4672-ba29-6a7afbb0b781.png)

**Comment by alexisdavidson** [comment]
Same issue

**Comment by leorissi** [comment]
Same issue too

**Comment by CH-JohnathanEvans** [comment]
Just installed it and am getting the same error. I have Node v19 on MacOS v12.6.2

**Comment by cylwin** [comment]
Same issue with node v16.15.1 and v18.13.0

**Comment by cylwin** [comment]
The bug come from :
https://www.npmjs.com/package/@oclif/core?activeTab=versions

The version is not fixed and there is an issue since they published the 2.0.0-beta that npm install as a dependency instead of 1.xxx
Not found a way to force the version for the moment as it's deep in dependencies.

**Comment by cylwin** [comment]
I found a workaround : 
Go to your global node_modules folder, replace the package.json of zcli and run npm i : 

working package.json : https://github.com/cylwin/zcli/blob/9d7969337a6ed9eb1cf7a913fa27242a4bb06789/package.json

So you can work on your zendesk app during the weekend :-) waiting the zendesk team to fix the issue better.

**Comment by NeoArcanjo** [comment]
> I found a workaround : 
> Go to your global node_modules folder, replace the package.json of zcli and run npm i : 
> 
> working package.json : https://github.com/cylwin/zcli/blob/9d7969337a6ed9eb1cf7a913fa27242a4bb06789/package.json
> 
> So you can work on your zendesk app during the weekend :-) waiting the zendesk team to fix the issue better.

I'll try

**Comment by alexisdavidson** [comment]
Thanks for the fix. It looks like the npm package hasn't been updated yet. Is there a way to get this fix right away?

**Comment by CH-JohnathanEvans** [comment]
Agreed. So, why was this closed?

**Comment by schuob** [comment]
@CH-JohnathanEvans `npm uninstall @zendesk/zcli -g` and reinstall it it will work.
