### ISSUE TITLE
zcli login fails with TypeError: Cannot read properties of undefined (reading 'ux')

### ISSUE THREAD

**Issue by vhartikainen** [zendesk/zcli#156]
## Expectations

Expected to login to Zendesk with following
```
$ zcli login -i 
```

## Reality

Throws an error: 
`TypeError: Cannot read properties of undefined (reading 'ux')`

## Steps to Reproduce

1. Install the zcli tool
2. Try to login with `zcli login -i` 

### Issue details

- Command: zcli login -i 
- Version: @zendesk/zcli/1.0.0-beta.28 darwin-arm64 node-v18.13.0
- OS: MacOS

**Comment by leorissi** [comment]
Same problem, we are waiting for a answer here too

**Comment by DaniloRSantos** [comment]
Same problem, we are waiting for a answer here too
