### ISSUE TITLE
`apps:server` command should allow params skipping similar to zat server

### ISSUE THREAD

**Issue by sarmadsangi** [zendesk/zcli#16]
## Expectations

`zcli apps:server` will prompt for missing param options but it does not allow you to skip with Return key like zat.
<img width="669" alt="93297631-f5214a00-f7f1-11ea-9b3c-8cd89ba61a9f" src="https://user-images.githubusercontent.com/640416/93298688-0a6c9780-f837-11ea-8328-8c0e9862af4e.png">

### Issue details

- Command: `zcli apps:server`
- Version:  all
- OS: all

**Comment by pgrzesiak** [comment]
Hi @sarmadsangi 👋  Will someone take care of this issue? We're working on an App Framework tutorial where we use ZCLI for an app development and it's problematic for us. By the way, is there any workaround?

**Comment by sarmadsangi** [comment]
@pgrzesiak this is resolved.
