### ISSUE TITLE
Using the cli as part of a ALM process

### ISSUE THREAD

**Issue by dafunkphenomenon** [zendesk/zcli#18]
Hi
Just reading through the docs for the cli and I'm after a bit of clarification. I'd like to try and use this is part of our devops process to build and push this right through to pushing it out into the production environment.

Am I correct in thinking that this command would be the one that would push in into our Zendesk site?
zcli apps:update

If that's correct, is there a way that I can do an unattended login, the docs for login seem to suggest (by its absence) that it's not possible. I'd need to be able to pass the credentials as parameters from the release process call to login to then be able to package (correctly) and push the package to the server. 
For clarification I'm using Azure Dev Ops.

Hope this makes sense and thanks in advance for any help you can give.

Matt

**Comment by sarmadsangi** [comment]
Hi @dafunkphenomenon,

For unattended login in CI/CD environment you can set `ZENDESK_SUBDOMAIN`, `ZENDESK_EMAIL` and `ZENDESK_API_TOKEN` environment variables.
https://github.com/zendesk/zcli/blob/master/docs/login.md
