### ISSUE TITLE
ZCLI Theme Preview not working with host mapped sub domains

### ISSUE THREAD

**Issue by hamishlang** [zendesk/zcli#193]
## Expectations

When using Theme:preview you're unable to set the URL as the host mapped one. If you use the standard Zendesk URL and preview a theme on a host mapped URL, any links pressed within the page directing the user to the host mapped URL will prevent the preview from being enabled. 

## Reality
 help.mywebsite.com won't work, but mywebsite.zendesk.com will.

## Steps to Reproduce

1. Use a host mapped URL as a domain
2. Navigate to a host mapped link when previewing a theme and the preview will cut off. 

### Issue details

- Command: 
- Version: Fresh install today
- OS: OSX 13.2.1

**Comment by luis-almeida** [comment]
We've added support for logging in with both the `subdomain` and the `domain` in the latest version `1.0.0-beta.38`:
https://github.com/zendesk/zcli/blob/master/docs/login.md#zcli-login-1

I believe this should allow you have a `profile` on the host mapped account and have theme preview work as expected.
Can you try it and let us know if you still experience preview cutting off?
