### ISSUE TITLE
zcli themes:import fails with 1 brand

### ISSUE THREAD

**Issue by peterpiek1** [zendesk/zcli#194]
## Expectations

`zcli themes:import`
Theme imported successfully theme ID: 01234567-0123-0123-0123-0123456789ab
...

## Reality

`zcli themes:import`
Creating theme import job... !
 ›   Error: TypeError - Value `360000123456` for /job/attributes/brand_id is of type `number`; expected `string`

## Steps to Reproduce

1. Only one brand in https://{subdomain}.zendesk.com/api/v2/brands.json
1. Change to theme directory
2. Execute `zcli themes:import`

### Issue details

- Command: `zcli themes:import`
- Version: @zendesk/zcli/1.0.0-beta.35 wsl-x64 node-v20.0.0
- OS: Windows 11, WSL2, Ubuntu 22.04.2 LTS

## Possible solution

If there are multiple brands the brand_id value is converted to a string.

If there is only one brand the brand_id value returned is a number, see:
https://github.com/zendesk/zcli/blob/fb0242c3d4ef04b3b9ad6cbfa2595439a07b35ca/packages/zcli-themes/src/lib/getBrandId.ts#L13C7-L13C26

Fix: change `return brands[0].id` to `return brands[0].id.toString()`
Now the import succeeds.

**Comment by luis-almeida** [comment]
Thanks for opening the issue 🙏🏼 
Closing it as this as been fixed in [1.0.0-beta.36](https://github.com/zendesk/zcli/compare/v1.0.0-beta.35...v1.0.0-beta.36)
