### ISSUE TITLE
Unable to run themes:preview without specifying profile

### ISSUE THREAD

**Issue by equalsgibson** [zendesk/zcli#208]
## Expectations

When setting environment variables to be used with ZCLI, I expect to be able to run commands and be authenticated.

## Reality

After setting the following environment variables: 

- ZENDESK_API_TOKEN 
- ZENDESK_EMAIL      
- ZENDESK_SUBDOMAIN 

 And running `zcli themes:preview`, I get the following error:

```bash
ubuntu@dev-cgibson:~/git/zendesk-theme/dist$ zcli themes:preview
Uploading theme... Ok
/usr/lib/node_modules/@zendesk/zcli/node_modules/@zendesk/zcli-themes/dist/commands/themes/preview.js:60
            const { subdomain, domain } = await new zcli_core_1.Auth().getLoggedInProfile();
                    ^

TypeError: Cannot destructure property 'subdomain' of '(intermediate value)' as it is undefined.
    at Server.<anonymous> (/usr/lib/node_modules/@zendesk/zcli/node_modules/@zendesk/zcli-themes/dist/commands/themes/preview.js:60:21)

Node.js v18.17.0
```

This appears to be an issue with the following code, where an assumption is made that the subdomain will always be coming from the logged in profile:

`/usr/lib/node_modules/@zendesk/zcli/node_modules/@zendesk/zcli-themes/dist/commands/themes/preview.js`
```javascript
        server.listen(port, host, async () => {
            // preview requires authentication so we're sure
            // to have a logged in profile at this point
            const { subdomain, domain } = await new zcli_core_1.Auth().getLoggedInProfile();
            const baseUrl = (0, zcli_core_1.getBaseUrl)(subdomain, domain);
            this.log(chalk.bold.green('Ready', chalk.blueBright(`${baseUrl}/hc/admin/local_preview/start`, '🚀')));
            this.log(`You can exit preview mode in the UI or by visiting ${baseUrl}/hc/admin/local_preview/stop`);
            tailLogs && this.log(chalk.bold('Tailing logs'));
        });
```

**TEMPORARY FIX**
For my use case, I was able to resolve this by editing the above file and changing: 
```javascript
const { subdomain, domain } = await new zcli_core_1.Auth().getLoggedInProfile();
const baseUrl = (0, zcli_core_1.getBaseUrl)(subdomain, domain);
```

to:

```javascript
// const { subdomain, domain } = await new zcli_core_1.Auth().getLoggedInProfile();
// const baseUrl = (0, zcli_core_1.getBaseUrl)(subdomain, domain);
const baseUrl = (0, zcli_core_1.getBaseUrl)("mysubdomain", "zendesk.com");
```

## Steps to Reproduce

1. Uninstall & reinstall the latest version of zcli globally: `sudo npm uninstall -g @zendesk/zcli; sudo npm install @zendesk/zcli -g`
1. Set your environment variables and resource your shell
1. Check your environment variables are set
2. Run zcli themes:preview 

### Issue details

- Command: zcli themes:preview
- Version: @zendesk/zcli/1.0.0-beta.39 linux-x64 node-v18.17.0
- OS: 
```bash
ubuntu@dev-cgibson:~/git/zendesk-theme$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by luis-almeida** [comment]
@equalsgibson thanks for a good the issue report!

Support for env variables when running `themes:preview` was added/fixed in [PR#239](https://github.com/zendesk/zcli/pull/239) and is now released in [v1.0.0-beta.43](https://github.com/zendesk/zcli/blob/master/CHANGELOG.md#100-beta43-2024-07-10).

I am closing this issue for now so please open another one if you still experience any issues.
