### ISSUE TITLE
Ability to test an app with secure settings locally

### ISSUE THREAD

**Issue by TheBox193** [zendesk/zcli#22]
## Expectations
If an app has secure settings, Testing an app with secure settings should locally work.

* Adding a `--app-id=` argument to `zcli app:server` similar to `zat server --app-id=123456789`

ZAT Server docs on `app-id`: https://developer.zendesk.com/apps/docs/developer-guide/using_sdk#testing-an-app-with-secure-settings-locally

## Reality

Local app can't proxy secure settings.

## Steps to Reproduce

1. Create a JS app that uses `const client = ZAFClient.init()` and `client.request(...)` or uses a secure setting.
1. Create a secure setting for the app
1. Attempt to sue the setting when using ZCLI

### Issue details

- Command: zcli app:server
- Version: 1.0.0-beta.4 darwin-x64 node-v15.2.0
- OS: Mac

**Comment by sarmadsangi** [comment]
Hey @TheBox193, this issue has be resolved now. We can now pass installation id via `zcli.apps.config.json` 
https://github.com/zendesk/zcli/blob/master/docs/apps.md#zcli-apps

```
{
  "plan": "silver",
  "app_id": 123,
  "installation_id": 12434234,
  "parameters": {
    "someToken": "fksjdhfb231435",
    "someSecret": 123
  }
}
```

I am closing this now, but feel free to me ping if above solution does not work for your use-case. 

Cheers!

**Comment by TheBox193** [comment]
@sarahjmiller Your amazing! We'll give it a go this week & I'll report back. Cheers! 👍

**Comment by metasal1** [comment]
Local app still cannot use proxy secure settings.
