### ISSUE TITLE
Directory name not working

### ISSUE THREAD

**Issue by aiavci** [zendesk/zcli#226]
## Reality
 it never respects the directory name.

<img width="298" alt="image" src="https://github.com/zendesk/zcli/assets/11793762/f2feba45-2b49-4065-bf15-5a1163fc9c39">

## Steps to Reproduce

1. Run `npx @zendesk/zcli apps:new` (I tried installing globally too so that's not it)
2. Enter directory name (Full name, half name, with and without quotes. Tried all of these)
3. Enter rest of info

### Issue details

- Command: `npx @zendesk/zcli apps:new`
- Version: Current latest
- OS:  MacOS Sonoma
- NPM version: 10.2.3
- Node version: v18.19.0
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]

**Comment by brianjohnpenner** [comment]
Same thing happens to me.

**Comment by tomkerswill** [comment]
This is the same for me.  I'm then not able to follow the rest of the getting started guides.  I'm not able to start a server, either - as it says the directory name is invalid.

**Comment by aiavci** [comment]
In case you're still having this issue: I simply downloaded the scaffold and just changed it locally 
https://github.com/zendesk/app_scaffolds

**Comment by anushkafka** [comment]
@aiavci Thank you very much, we have included a fix for this in our latest release `v1.0.0-beta.42`
