### ISSUE TITLE
Axios throws on all commands

### ISSUE THREAD

**Issue by mmasiulis** [zendesk/zcli#265]
When running commands like `zcli login`, `zcli apps:update`, command line throws this:

```
AxiosError: There is no suitable adapter to dispatch the request  - adapter fetch is not supported by the environment
    Code: ERR_NOT_SUPPORT
```

**Comment by anushkafka** [comment]
Hi @mmasiulis can you provide some information about your environment like OS, node version please?

**Comment by mmasiulis** [comment]
MacOS Sonoma, node v20.11.0, however, I've used also node v16.20.1 as well and the issue was persisting. I've been using ` @zendesk/zcli/1.0.0-beta.50` version

**Comment by tomasspangelo** [comment]
This happens to us as well when using github action workflow (runs on ubuntu-latest). After you migrated to using the axios fetch adapter our entire deployment pipeline fails...

**Comment by anushkafka** [comment]
@mmasiulis @tomasspangelo I am not able to reproduce this at the moment. Can you please ensure your node version is v20 or later while we continue to look into this?

**Comment by tomasspangelo** [comment]
@anushkafka I upgrade the node version to 20.x now and it works fine, thank you! We were using 16.x to begin with so it was about time with an upgrade

**Comment by anushkafka** [comment]
@mmasiulis were you able to verify your node.js version is v20 or later?

**Comment by mmasiulis** [comment]
@anushkafka Indeed, using node v20 worked. We as well need to update our pipelines to use newer node versions. Thanks for help!
