### ISSUE TITLE
zcli apps:new command does not work for absolute paths

### ISSUE THREAD

**Issue by sarmadsangi** [zendesk/zcli#35]
![Screen Shot 2021-02-15 at 12 07 46 pm](https://user-images.githubusercontent.com/640416/108002254-20c78b00-7043-11eb-88d1-5f97a95722f7.png)

## Steps to Reproduce

1. run `zcli apps:new`
2. pass absolute path when prompted for dir name
3. you will get an error during scaffold copy

### Issue details

- Command: zcli apps:new
- Version: beta.6
- OS: all

**Comment by JeanMarcGoepfert** [comment]
Verified this is no longer an issue on latest version.

<img width="992" alt="Screenshot 2024-06-13 at 2 12 34 pm" src="https://github.com/zendesk/zcli/assets/4322064/3d6ff789-9d0c-4085-b033-14f7e2e9b34a">
