### ISSUE TITLE
I got stuck on what the login script wanted for subdomain

### ISSUE THREAD

**Issue by scottyloewenjr** [zendesk/zcli#39]
I kept entering my whole subdomain when all I really needed was the first part, the 'client' of 'client.zendesk.com'. 

This is all figured out now, but I thought I would drop a suggestion for the next person that comes along!

**Comment by sarmadsangi** [comment]
Hey @scottyloewenjr Thanks for the feedback, we realised that is indeed confusing sometimes. We are thinking of accepting both in future.

I ll leave this open for now, so we track this.

**Comment by JeanMarcGoepfert** [comment]
This issue was resolved in https://github.com/zendesk/zcli/pull/32.
