### ISSUE TITLE
Validation error on newly created apps — Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by forestanderson** [zendesk/zcli#41]
![image](https://user-images.githubusercontent.com/930865/110494619-c5c50900-80c1-11eb-9a75-a9536afa9df2.png)

## Steps to Reproduce

1. Run `zcli apps:new`
1. Run `zcli apps:validate` or `zcli apps:package` on the newly created app (or any other app).

### Issue details

- Command: `zcli apps:validate` and `zcli apps:package`
- Version: 1.0.0-beta.4
- OS: macOS

**Comment by sarmadsangi** [comment]
```
➜  zd-sidebar-test zcli apps:package .
 ›   Error: FetchError: invalid json response body at https://z3nsarmad.zendesk.com/api/v2/apps/validate reason: Unexpected token T in JSON at position 0
 ```
 
 
 ^ this happens due to missing or invalid credentials and response body is in text which we fail to parse as we expect it to be json. I ll keep this issue open till we parse this and show a meaningful message.

**Comment by sostopher** [comment]
This is fixed by https://github.com/zendesk/zcli/pull/42, thanks for reporting!
