### ISSUE TITLE
ZCLI Login Failing

### ISSUE THREAD

**Issue by BhushanVasisht** [zendesk/zcli#43]
zcli login -i failing.

Same credentials work in browser but failing for interactive login

<img width="682" alt="Screen Shot 2021-03-12 at 10 19 06 AM" src="https://user-images.githubusercontent.com/43195788/110967823-6adb1e00-831c-11eb-9f00-36ec1492ae7a.png">

- Command: zcli apps login
- Version: @zendesk/zcli/1.0.0-beta.7 darwin-x64 node-v12.21.0
- OS: mac os 11.2.3

**Comment by Nevyn357** [comment]
Seeing the same on Win10 20h4
@zendesk/zcli/1.0.0-beta.7 win32-x64 node-v12.16.2

**Comment by kartikmax** [comment]
where to enable password access

**Comment by Mannclaudiu** [comment]
> where to enable password access

It appears that it changed the location of password access
Now you have to go under **Apps and Integrations > Zendesk API** and then enable that slide
![image](https://user-images.githubusercontent.com/22660140/195266754-012bd470-068e-4d4f-87c6-513de6b85469.png)
