### ISSUE TITLE
zcli apps:server -config flag for zcli.apps.config.json is not supported when working locally

### ISSUE THREAD

**Issue by kristinburton** [zendesk/zcli#58]
## Expectations
The `apps:server` command does not support the `-config` flag when needing to use `zli.apps.config.json`. While working locally with zat, the developer can run `zat server -c .config.json` and the command will automatically populate all of the values of the app settings from the config file versus manually entering each value of the settings in the terminal. This is crucial for developing locally and it is a huge time save during a project since some apps can have up to 20 settings. 

## Reality
Unable to run the -config flag due to zcli supporting multiple apps at the moment

## Steps to Reproduce

1. Open terminal to run zcli apps:server APP_FOLDER_PATH
2. Manually enter every value for the app settings. 
3. `zli.apps.config.json` is currently a useless file

### Issue details

- Command: zcli apps:server
- Version: @zendesk/zcli/1.0.0-beta.8 darwin-x64 node-v14.15.4
- OS: all

**Comment by 3Scribe** [comment]
Just had a look at the code as I was having the same problem and I found these commented out lines: 

```
    // TODO: custom file is not supported for other commands,
    // lets come back to this in near future
    // config: flags.string({ default: 'zcli.apps.config.json', description: 'Configuration file for zcli::apps' })
```

So it looks like the default settings have been put on the long finger for the moment.  I might have a look to see what's involved and maybe take it on for my next branch to work on.

**Comment by Matenko** [comment]
Is there any update or work around for this? We won't be able to move over to zcli until we can use a config file since we have multiple apps all with different configs for different environments.

**Comment by DerJacques** [comment]
In addition to providing the `config` as a parameter, it would be lovely if the `appId` could be passed as a CLI parameter as well. This was possible with ZAT and made it much easier to work with the same app across multiple instances.

**Comment by ashwinkshenoy** [comment]
hello team,
Any updates on this issue?
It will really help the dev team here @zd!

**Comment by anushkafka** [comment]
Hi everyone, once you have included the parameter values in `zcli.apps.config.json` you will not get prompted to enter the values again unless the parameter has `secure = true`. This is operational without any additional flags such as -config.
