### ISSUE TITLE
App server doesn't stay running after typo correction

### ISSUE THREAD

**Issue by jamesratcliffe** [zendesk/zcli#61]
## Expectations

App is served and server process keeps running.

## Reality

Server process exits right away

## Steps to Reproduce

1. Run `zlci apps:serve` [sic]
2. zcli will offer to correct your typo to `apps:server`. Enter `y`.

### Issue details

- Command: zcli apps server
- Version: 1.0.0-beta.8
- OS: Mac (darwin-x64 node-v16.3.0)

**Comment by jamesratcliffe** [comment]
Very minor, but I thought it would still be helpful to report it.

**Comment by anushkafka** [comment]
Thank you for reporting, closing this issue as it has been fixed.
