### ISSUE TITLE
Live Reloading Support for zcli apps:server

### ISSUE THREAD

**Issue by zach-anthony** [zendesk/zcli#62]
## Feature

While you are able to reload the app inside the Zendesk product which will incorporate changes you have made to your app, this doesn't take in changes made to the `manifest.json` file. It would be good to be able to live reload changes to the manifest as well as the rest of your app assets and reload the app in browser automatically without having to restart the development server and reload the app in product similar to [this](https://dev.to/cassiolacerda/automatically-refresh-the-browser-on-node-express-server-changes-x1f680-1k0o)

### Issue details

- Command: `zcli apps:server`
- Version: `@zendesk/zcli/1.0.0-beta.8 darwin-x64 node-v14.17.1`
- OS: `macOS Big Sur 11.4 (20F71)`

**Comment by etanxing** [comment]
The enhancement fix is in PR https://github.com/zendesk/zcli/pull/90 and merged into `master`.
