### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by viperfx** [zendesk/zcli#80]
## Expectations

When I login with my sponsored zendesk dev account, it should allow me to login.

## Reality

I got the error: Failed to log in to your account:

Even though I am able to use the same credentials to login to web portal.

## Steps to Reproduce

1. zcli login -i
2. enter credentials

### Issue details

- Command:  zcli login -i
- Version: @zendesk/zcli/1.0.0-beta.8 darwin-arm64 node-v14.18.0
- OS: macOS 11.6

**Comment by MSicuroTP** [comment]
I've also been running into this, I've tried setting the environment variables with both options (Subdomain/Email/Password and Subdomain/Email/API Token). Also both the Password Access and Token Access are enabled in the Admin Center Settings. 

Are there any other steps to troubleshoot not being able to login with zcli?

**Comment by mrnmilutinovic** [comment]
@MSicuroTP have you specified your subdomain as a full domain name or just the prefix? 
This actually worked for me in this setup: 

- `Node 16.16.0`
- `NVM 0.39.1`
- `@zendesk/zcli/1.0.0-beta.16 darwin-arm64 node-v16.16.0`

And I was using this command: 
`zcli -s <<your-subdomain>>.zendesk.com -i`
